server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: post-service
  kafka:
    consumer:
      group-id: post-service-id
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
  datasource:
    password: ${DB_PASSWORD}
    username: ${USER_NAME}
    url: ${POST_SERVICE_DATABASE_URL:jdbc:postgresql://localhost:5432/post-service}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none

jwt:
  secret-code: ${SECRET_KEY}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}

springdoc:
  swagger-ui:
    path: /docs/